run:
  timeout: 5m

linters:
  enable:
    - govet
    - gosimple
    - staticcheck
    - unused
    - errcheck
    - gofmt
    - goimports
    - revive

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
