linters:
  disable:
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
      - name: receiver-naming
        disabled: true
      - name: error-strings
        disabled: true
